dinesh

high

# Failed transfer with low level call could be overlooked

## Summary
Here Failed transfer with low level call does not check for the existence of the contract being called.

## Vulnerability Detail
At https://github.com/sherlock-audit/2023-01-uxd/blob/main/contracts/core/UXDController.sol#L304
`        (bool success,) = receiver.call{value: amountOut}("");`

## Impact
    If the contract being called does not exist, the call will simply fail and return a default value (usually false for a boolean return value or 0 for a numeric return value).
    If the contract being called exists but is not able to handle the call (for example, if it does not have a function with the correct signature), the call will also fail and return a default value.
    If the contract being called exists and is able to handle the call, but the call results in an exception being thrown by the contract, the call will also fail and the exception will be propagated back to the calling contract. This can potentially cause the calling contract to throw an exception as well, or to behave unexpectedly.

## Tool used

Manual Review

## Recommendation
Check for contract existence on low-level calls, so that failures are not missed.